config/routes.rb
Rails.application.routes.draw do
  resources :actors
  get 'users/show'
  resources :directors
  resources :movie_reviews
  devise_for :users
  root 'static_pages#home'
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'ムービー', root_path, class:"navbar-brand" %>
   <!--  <a class="navbar-brand" href="#">ムービー</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link" %> </li>
        <% else %>
        <li class="nav-item"><%= link_to "サインイン", new_user_session_path, class:"nav-link" %> </li>
        <li class="nav-item"><%= link_to "ユーザ登録", new_user_registration_path, class:"nav-link" %><li>
        <% end %>
        <li class="nav-item"><%= link_to "ディレクター", directors_path, method: :get, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "アクター", actors_path, method: :get, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "映画", movies_path, method: :get, class:"nav-link" %><li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/home.html.erb
<h1>映画レビューサイトへようこそ</h1>