config/routes.rb
Rails.application.routes.draw do
  resources :actors
  get 'users/show'
  resources :directors
  resources :movie_reviews
  devise_for :users
  root 'static_pages#home'
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movie_reviews_controller.rb
class MovieReviewsController < ApplicationController
  before_action :set_movie_review, only: %i[ show edit update destroy ]

  # GET /movie_reviews or /movie_reviews.json
  def index
    @movie_reviews = MovieReview.all
  end

  # GET /movie_reviews/1 or /movie_reviews/1.json
  def show
      @user = current_user
  end

  # GET /movie_reviews/new
  def new
    @user = current_user
    @movie_review = MovieReview.new
  end

  # GET /movie_reviews/1/edit
  def edit
  end

  # POST /movie_reviews or /movie_reviews.json
  def create
    @movie_review = MovieReview.new(movie_review_params)
    @movie_review.user_id = current_user.id
    # @book_review.user_id = current_user.id
    # @book_review.user_id = 1
    
    respond_to do |format|
      if @movie_review.save
        url = "/movies/" + @movie_review.movie_id.to_s
        format.html { redirect_to url, notice: "Movie review was successfully created." }
        format.html { redirect_to @movie_review, notice: "Movie review was successfully created." }
        format.json { render :show, status: :created, location: @movie_review }
      else
        format.html { render :new }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_reviews/1 or /movie_reviews/1.json
  def update
    respond_to do |format|
      if @movie_review.update(movie_review_params)
        format.html { redirect_to @movie_review, notice: "Movie review was successfully updated." }
        format.json { render :show, status: :ok, location: @movie_review }
      else
        format.html { render :edit }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_reviews/1 or /movie_reviews/1.json
  def destroy
    @movie_review.destroy
    respond_to do |format|
      format.html { redirect_to movie_reviews_url, notice: "Movie review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_review
      @movie_review = MovieReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_review_params
      params.require(:movie_review).permit(:user_id, :movie_id, :review)
    end
end

app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

app/views/movie_reviews/_form.html.erb
<%= form_with(model: movie_review, local: true) do |form| %>
  <% if movie_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_review.errors.count, "error") %> prohibited this movie_review from being saved:</h2>

      <ul>
        <% movie_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :user_id,"ユーザーのID", class:"form-label"%>
    <%= form.number_field :user_id, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :movie_id, "映画のID", class:"form-label"%>
    <%= form.number_field :movie_id, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :review, "レビュー", class:"form-label"%>
    <%= form.text_area :review, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/movie_reviews/edit.html.erb
<h1>Editing Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Show', @movie_review %> |
<%= link_to 'Back', movie_reviews_path %>

app/views/movie_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>映画のレビュー</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_reviews.each do |movie_review| %>
      <tr>
        <td><%= movie_review.user_id %></td>
        <td><%= movie_review.movie_id %></td>
        <td><%= movie_review.review %></td>
        <td><%= link_to '見せる', movie_review, method: :get, class:"btn btn-success"  %></td>
        <td><%= link_to '修正', edit_movie_review_path(movie_review), method: :get, class:"btn btn-warning" %></td>
        <td><%= link_to '削除', movie_review, method: :delete, data: { confirm: 'Are you sure?', class: "btn btn-info" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しい映画のレビューの追', new_movie_review_path %>

app/views/movie_reviews/new.html.erb
<h1>New Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Back', movie_reviews_path %>

app/views/movie_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ユーザーのID:</strong>
  <%= @movie_review.user_id %>
</p>

<p>
  <strong>映画のID:</strong>
  <%= @movie_review.movie_id %>
</p>

<p>
  <strong>レビュー:</strong>
  <%= @movie_review.review %>
</p>

<%= link_to 'Edit', edit_movie_review_path(@movie_review) %> |
<%= link_to 'Back', movie_reviews_path %>