config/routes.rb
Rails.application.routes.draw do
  resources :actors
  get 'users/show'
  resources :directors
  resources :movie_reviews
  devise_for :users
  root 'static_pages#home'
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
      @movie_review = MovieReview.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description, :length, :directors, :actors, :category, :image)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3" >
    <%= form.label :title, "タイトル", class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, "インフォメーション", class:"form-label" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :length, "長さ", class:"form-label" %>
    <%= form.number_field :length, class:"form-control" %>
  </div>

   <div class="field mb-3">
    <%= form.label :directors, "ディレクター", class:"form-label" %>
    <%= form.text_area :directors, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :actors, "アクター", class:"form-label" %>
    <%= form.text_area :actors, class:"form-control" %>
  </div>

 <div class="field mb-3">
    <%= form.label :category, "カテゴリー", class:"form-label" %>
    <%= form.text_field :category, class:"form-control" %>
  </div>
  
  <div class="field mb-3">
      <%= form.label :image, "写真", class:"form-label" %>
      <%= form.file_field :image, class:"form-control" %><br>
   </div>

  <div class="actions">
    <%= form.submit class:"btn btn-danger" %>
  </div>
  
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>映画</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>インフォメーション</th>
      <th>長さ</th>
      <th>ディレクター</th>
      <th>アクター</th>
      <th>カテゴリー</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.length %></td>
        <td><%= movie.directors %></td>
        <td><%= movie.actors %></td>
        <td><%= movie.category %></td>
        <td><%= link_to '見せる', movie, method: :get, class:"btn btn-success" %></td>
        <td><%= link_to '修正', edit_movie_path(movie), method: :get, class:"btn btn-warning" %></td>
        <td><%= link_to '削除', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しい映画の追加', new_movie_path, method: :get, class:"btn btn-primary" %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<br>

<%= link_to 'Back', movies_path, class:"btn btn-primary" %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>インフォメーション:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>長さ:</strong>
  <%= @movie.length %> 分
</p>

<p>
  <strong>ディレクター:</strong>
  <%= @movie.directors %>
</p>

<p>
  <strong>アクター:</strong>
  <%= @movie.actors %>
</p>

<p>
  <strong>カテゴリー:</strong>
  <%= @movie.category %>
</p>

<p>
  <% if @movie.image.attached? %>
    <%= image_tag @movie.image %>
  <% end %>
</p>

<p>レビュー</p>
  <%= form_with(model: @movie_review, local: true) do |form| %>
    <div class= "field">
      <%= form.text_area :review %>
      <%= form.hidden_field :movie_id, :value => @movie.id %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  <% end %>
  <br>
  
  <p>レビュー リスト</p>
   <ul>
     <% @movie.movie_review.each do |movie_review|%>
       <li><%= movie_review.review %>
     (<i><%= movie_review.user.name if movie_review.user%></i>)</li>
     <% end %>
   </ul>


  
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %> 