config/routes.rb
Rails.application.routes.draw do
  resources :actors
  get 'users/show'
  resources :directors
  resources :movie_reviews
  devise_for :users
  root 'static_pages#home'
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/director.rb
class Director < ApplicationRecord
    has_one_attached :image
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[ show edit update destroy ]

  # GET /directors or /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1 or /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors or /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: "Director was successfully created." }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1 or /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: "Director was successfully updated." }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1 or /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: "Director was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def director_params
      params.require(:director).permit(:name, :career, :awards, :image)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_with(model: director, local: true) do |form| %>
  <% if director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
        <% director.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field mb-3">
    <%= form.label :career, class:"form-label" %>
    <%= form.text_area :career, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :awards, class:"form-label" %>
    <%= form.text_area :awards, class:"form-control" %>
  </div>

  <div class="field mb-3">
      <%= form.label :image, class:"form-label" %>
      <%= form.file_field :image, class:"form-control" %><br>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing Director</h1>

<%= render 'form', director: @director %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ディレクター</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>名前</th>
      <th>キャリア</th>
      <th>受賞</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= director.career %></td>
        <td><%= director.awards %></td>
        <td><%= link_to '見せる', director, class:"btn btn-success", method: :get %></td>
        <td><%= link_to '修正',  edit_director_path(director), class:"btn btn-warning", method: :get %></td>
        <td><%= link_to '削除', director, method: :delete, class: "btn btn-info", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいディレクターの追加',  new_director_path, method: :get, class:"btn btn-primary" %>

app/views/directors/new.html.erb
<h1>New Director</h1>

<%= render 'form', director: @director %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @director.name %>
</p>

<p>
  <strong>Career:</strong>
  <%= @director.career %>
</p>

<p>
  <strong>Awards:</strong>
  <%= @director.awards %>
</p>

<p>
  <% if @director.image.attached? %>
    <%= image_tag @director.image %>
  <% end %>
</p>

<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>